export enum Tool {
  DASHBOARD = 'DASHBOARD',
  IMAGE_GEN = 'IMAGE_GEN',
  IMAGE_EDIT = 'IMAGE_EDIT',
  IMAGE_ANALYZE = 'IMAGE_ANALYZE',
  VIDEO_GEN = 'VIDEO_GEN',
  VIDEO_ANALYZE = 'VIDEO_ANALYZE',
  VOICE_ASSISTANT = 'VOICE_ASSISTANT',
  TTS = 'TTS',
  CHAT = 'CHAT',
}
